<?php

namespace AppBundle\Repository;

/**
 * FicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * [getOpenedProjects description]
     * @return [type] [description]
     */
    public function getFilterFiches($id) {
        return $this->createQueryBuilder('f')
                ->where('f.projetEx = :id')
                ->setParameter('id', $id)       
        ;
    }
}
